server:
  port: 8090
  servlet:
    context-path: /api
mybatis-plus:
  typeAliasesPackage: com.sharding.demo.model
  mapper-locations: classpath*:com/sharding/demo/mapper/*.xml
  configuration:
    #是否开启自动驼峰命名规则
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

#数据库连接
spring:
  shardingsphere:
    props:
      sql:
        show: true
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shard_order_0?characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shard_order_1?characterEncoding=utf8&serverTimezone=UTC
        username: root
        password: root
    sharding:
      default-database-strategy:
        inline:
          #根据用户id来区分到不同库
          sharding-column: user_id
          algorithm-expression: ds$->{user_id%2}
      tables:
        t_order:
          #配置数据节点
          actual-data-nodes: ds$->{0..1}.t_order_$->{1..2}
          #指定表主键生成策略,雪花算法
          key-generator:
            column: order_id
            type: SNOWFLAKE
          #分片策略和分片算法
          table-strategy:
            inline:
              sharding-column: order_id
              algorithm-expression: t_order_$->{order_id % 2+ 1}
